import { LegalDocument } from "@/components/legal/legal-document";

const CONTENT = `
CONSENT AND RELEASE AGREEMENT

Effective Date: [Insert Date]

Last Updated: [Insert Date]

PLEASE READ THIS CONSENT AND RELEASE AGREEMENT CAREFULLY.

By creating an account, accessing, or using VA (Vocal + Acuity), you acknowledge that you have read, understood, and agreed to this Consent and Release Agreement.

If you do not agree, you must not use the Service.

=================================================================
1. PURPOSE OF THIS AGREEMENT
=================================================================

This Consent and Release Agreement explains:

- Your consent to participate in VA.
- Your consent to AI-powered coaching.
- Your consent to voice processing (if enabled).
- Your consent to assessments and Communication DNA profiling.
- Your acknowledgment of platform limitations.
- Your release of certain claims relating to the educational use of the platform.

=================================================================
2. PARTICIPATION CONSENT
=================================================================

I voluntarily choose to participate in VA.

I understand that VA is an AI-powered Corporate Communication Development Platform designed to support:

- Communication improvement
- Professional articulation
- Leadership communication
- Executive presence
- Interview preparation
- Presentation effectiveness
- Strategic communication
- Communication confidence

I understand that participation in VA is entirely voluntary.

=================================================================
3. CONSENT TO AI INTERACTIONS
=================================================================

I acknowledge and agree that:

- Interactions on VA may be generated by artificial intelligence systems.
- Responses may not be reviewed by a human.
- Artificial intelligence systems may occasionally produce inaccurate or incomplete responses.
- AI-generated content should not be treated as professional advice.
- I am responsible for independently evaluating information provided through the platform.

I voluntarily consent to receiving AI-generated coaching, feedback, recommendations, assessments, and mentoring experiences.

=================================================================
4. CONSENT TO COMMUNICATION COACHING
=================================================================

I understand that VA provides communication coaching designed to enhance:

- Professional communication
- Executive communication
- Leadership communication
- Corporate communication
- Interview communication
- Presentation delivery
- Communication effectiveness

I acknowledge that coaching results may vary between individuals.

VA does not guarantee specific outcomes or improvements.

=================================================================
5. CONSENT TO ASSESSMENTS
=================================================================

I consent to participation in:

- Communication assessments
- Skill evaluations
- Progress assessments
- Development assessments
- Communication tracking activities

I understand that assessment outputs are intended solely for educational and development purposes.

I understand that assessments:

- Are not certifications.
- Are not employment evaluations.
- Are not academic evaluations.
- Are not psychological assessments.
- Are not professional qualifications.

=================================================================
6. CONSENT TO COMMUNICATION DNA PROFILING
=================================================================

I understand that VA may generate a personalized profile called:

"Communication DNA"

I acknowledge that Communication DNA may include:

- Communication preferences
- Communication tendencies
- Development opportunities
- Communication strengths
- Communication challenges

I understand that Communication DNA exists solely to personalize coaching and learning experiences.

I understand that Communication DNA:

- Is not a personality test.
- Is not psychological profiling.
- Is not a psychiatric assessment.
- Is not a medical diagnosis.
- Is not a professional certification.

I voluntarily consent to the generation and use of Communication DNA profiles within the platform.

=================================================================
7. CONSENT TO MENTOR MEMORY
=================================================================

I understand that VA may retain information from my interactions to improve future experiences.

This may include:

- Communication goals
- Learning preferences
- Previous discussions
- Progress history
- Coaching notes
- Assessment results

I consent to the storage and use of such information to personalize my coaching experience.

=================================================================
8. CONSENT TO VOICE PROCESSING
=================================================================

If I use voice features, I expressly consent to:

- Recording voice submissions provided by me.
- Processing voice recordings.
- Converting speech into text.
- Generating transcripts.
- Analyzing communication patterns.
- Producing communication assessments.
- Creating coaching recommendations.

I understand that voice features are optional.

I may discontinue use of voice features at any time.

=================================================================
9. ASSUMPTION OF RESPONSIBILITY
=================================================================

I understand and agree that:

- I remain solely responsible for my decisions.
- I remain solely responsible for my actions.
- I remain solely responsible for interpreting information provided through VA.
- I should seek qualified professional advice where necessary.

VA does not make decisions on my behalf.

=================================================================
10. NO PROFESSIONAL ADVICE
=================================================================

I understand that VA does not provide:

- Legal advice
- Financial advice
- Tax advice
- Investment advice
- Medical advice
- Mental health treatment
- Therapy
- Psychiatric services
- Employment advice

Any information provided through VA is educational in nature.

=================================================================
11. NO GUARANTEE OF RESULTS
=================================================================

I acknowledge that VA makes no guarantee regarding:

- Communication improvement
- Job offers
- Promotions
- Career advancement
- Leadership success
- Interview performance
- Business success
- Professional outcomes

Results depend on numerous factors beyond the control of VA.

=================================================================
12. RELEASE OF CLAIMS
=================================================================

To the fullest extent permitted by law, I release, waive, and discharge VA, its founders, officers, employees, contractors, affiliates, licensors, service providers, and partners from claims arising from:

- AI-generated content.
- Coaching recommendations.
- Communication assessments.
- Communication DNA profiles.
- Voice processing activities.
- Mentor interactions.
- Platform usage.
- Communication training outcomes.

This release applies except where prohibited by applicable law.

=================================================================
13. LIMITATION OF LIABILITY ACKNOWLEDGMENT
=================================================================

I acknowledge that:

- VA is provided on an "AS IS" basis.
- VA is provided on an "AS AVAILABLE" basis.
- No warranty is made regarding accuracy, reliability, or availability.
- Use of the platform is voluntary and undertaken at my own risk.

=================================================================
14. DATA PROCESSING ACKNOWLEDGMENT
=================================================================

I acknowledge that VA may process information described in:

- The Privacy Policy
- The Data Processing Notice
- The AI & Voice Processing Consent

I understand that use of the platform involves processing of personal information necessary to provide the Service.

=================================================================
15. CONSENT TO ELECTRONIC RECORDS
=================================================================

I consent to:

- Electronic agreements.
- Electronic disclosures.
- Electronic notices.
- Electronic communications.

I agree that electronic acceptance shall have the same legal effect as a handwritten signature where permitted by law.

=================================================================
16. WITHDRAWAL OF CONSENT
=================================================================

I understand that I may withdraw consent by:

- Discontinuing use of the Service.
- Deleting my account.
- Contacting VA regarding specific processing activities where applicable.

Withdrawal of consent may affect the availability of certain features.

=================================================================
17. ACKNOWLEDGMENT
=================================================================

BY USING VA, I ACKNOWLEDGE THAT:

- I have read this Consent and Release Agreement.
- I understand this Agreement.
- I voluntarily agree to this Agreement.
- I consent to AI-assisted coaching.
- I consent to communication assessments.
- I consent to Communication DNA generation.
- I consent to mentor memory functionality.
- I consent to voice processing where applicable.
- I understand that VA is not a provider of professional advice.
- I understand that AI systems may make mistakes.

=================================================================
18. CONTACT INFORMATION
=================================================================

For questions regarding this Agreement, contact:

VA (Vocal + Acuity)

Email: legal@yourdomain.com

Website: https://yourdomain.com

=================================================================
END OF CONSENT AND RELEASE AGREEMENT
=================================================================
`;

export default function Page() {
  return <LegalDocument title="Consent and Release Agreement" content={CONTENT} />;
}
