import { LegalDocument } from "@/components/legal/legal-document";

const CONTENT = `
PLATFORM DISCLAIMER

Effective Date: [Insert Date]

Last Updated: [Insert Date]

PLEASE READ THIS DISCLAIMER CAREFULLY BEFORE USING VA (VOCAL + ACUITY).

By accessing or using VA, you acknowledge and agree to the terms outlined in this Disclaimer.

=================================================================
1. PURPOSE OF THE PLATFORM
=================================================================

VA (Vocal + Acuity) is an AI-powered Corporate Communication Development Platform designed to support users in improving:

- Corporate communication
- Professional articulation
- Executive presence
- Leadership communication
- Presentation skills
- Interview performance
- Strategic thinking
- Communication confidence
- Communication intelligence

VA is intended solely for educational, developmental, training, coaching, and professional growth purposes.

=================================================================
2. AI-GENERATED CONTENT DISCLAIMER
=================================================================

VA utilizes artificial intelligence technologies to generate:

- Mentor responses
- Communication feedback
- Coaching recommendations
- Communication assessments
- Communication DNA profiles
- Progress insights
- Role-play interactions
- Discussion responses

Artificial intelligence systems may produce:

- Inaccurate information
- Incomplete information
- Outdated information
- Misleading information
- Unexpected responses

VA does not guarantee the accuracy, completeness, reliability, or suitability of any AI-generated content.

Users should independently evaluate all information provided by the platform.

=================================================================
3. NOT PROFESSIONAL ADVICE
=================================================================

VA does not provide:

- Legal advice
- Financial advice
- Investment advice
- Tax advice
- Medical advice
- Clinical advice
- Psychological advice
- Psychiatric advice
- Therapeutic services
- Employment advice
- Human resources advice
- Regulatory advice

Nothing provided through VA should be interpreted as professional advice of any kind.

Users should consult appropriately qualified professionals before making important legal, financial, medical, employment, investment, or business decisions.

=================================================================
4. NOT A THERAPIST OR COUNSELLOR
=================================================================

VA is not:

- A therapist
- A psychologist
- A psychiatrist
- A counsellor
- A mental health professional
- A crisis intervention service

VA does not diagnose, treat, prevent, cure, or manage any mental health, medical, psychological, emotional, or psychiatric condition.

If you are experiencing emotional distress, psychological difficulties, or a mental health crisis, seek assistance from appropriately qualified professionals or emergency services.

=================================================================
5. COMMUNICATION SCORES DISCLAIMER
=================================================================

VA may generate:

- Communication scores
- Assessment reports
- Executive presence ratings
- Confidence ratings
- Communication DNA profiles
- Progress scores
- Development recommendations

These outputs are:

- Algorithmic estimates
- Educational tools
- Developmental indicators

These outputs are NOT:

- Scientific measurements
- Professional certifications
- Employment evaluations
- Academic evaluations
- Psychological assessments
- Objective indicators of ability

Scores and ratings should be viewed as guidance tools only.

=================================================================
6. COMMUNICATION DNA DISCLAIMER
=================================================================

Communication DNA is a proprietary coaching and personalization feature developed for communication development purposes.

Communication DNA:

- Is not a personality assessment.
- Is not a psychometric evaluation.
- Is not a psychological diagnosis.
- Is not a professional certification.
- Is not an employment assessment.

Communication DNA is intended solely to personalize coaching experiences and support communication growth.

=================================================================
7. ROLE-PLAY AND SIMULATION DISCLAIMER
=================================================================

VA may provide simulated conversations involving:

- Executives
- Managers
- Investors
- Recruiters
- Board Members
- Customers
- Consultants
- Other professional personas

Role-play content is generated by artificial intelligence and is fictional in nature unless expressly stated otherwise.

Role-play scenarios should not be interpreted as reflecting actual individuals, organizations, employers, regulators, or institutions.

=================================================================
8. CAREER AND EMPLOYMENT DISCLAIMER
=================================================================

VA may provide communication coaching related to:

- Interviews
- Leadership
- Promotions
- Workplace communication
- Career development

VA does not guarantee:

- Employment
- Promotions
- Salary increases
- Business success
- Interview success
- Career advancement

Career outcomes depend on numerous factors outside the control of VA.

=================================================================
9. BUSINESS DECISION DISCLAIMER
=================================================================

VA may discuss topics relating to:

- Leadership
- Business strategy
- Negotiation
- Management
- Decision-making
- Communication

Users remain solely responsible for evaluating and implementing any business decisions.

VA accepts no responsibility for business, financial, operational, strategic, or commercial decisions made by users.

=================================================================
10. USER RESPONSIBILITY
=================================================================

Users acknowledge and agree that:

- They remain responsible for their decisions.
- They remain responsible for their actions.
- They remain responsible for evaluating information.
- They remain responsible for obtaining professional advice where required.

VA serves only as a communication coaching and development platform.

=================================================================
11. NO GUARANTEE OF RESULTS
=================================================================

Although VA is designed to support communication improvement, VA does not guarantee:

- Specific outcomes
- Skill improvements
- Learning outcomes
- Interview performance
- Presentation performance
- Leadership success
- Business success

Results vary by individual and depend on personal effort, commitment, circumstances, and external factors.

=================================================================
12. THIRD-PARTY TECHNOLOGIES
=================================================================

VA may utilize third-party technologies, including artificial intelligence providers, hosting providers, analytics providers, and infrastructure providers.

VA is not responsible for interruptions, inaccuracies, or issues arising from third-party systems.

=================================================================
13. LIMITATION OF LIABILITY
=================================================================

To the fullest extent permitted by law:

VA, its owners, officers, employees, contractors, affiliates, licensors, service providers, and partners shall not be liable for:

- Direct losses
- Indirect losses
- Incidental losses
- Consequential losses
- Economic losses
- Business losses
- Career losses
- Reputational losses
- Data losses

arising from:

- Use of the platform
- AI-generated content
- Assessments
- Communication DNA
- Mentor interactions
- Coaching recommendations
- Role-play experiences

Use of VA is entirely at the user's own risk.

=================================================================
14. EDUCATIONAL PURPOSES ONLY
=================================================================

All content provided through VA is intended for:

- Educational purposes
- Training purposes
- Self-improvement purposes
- Professional development purposes

Nothing on the platform should be interpreted as professional advice, guarantees of success, or expert consultation.

=================================================================
15. ACCEPTANCE OF THIS DISCLAIMER
=================================================================

By using VA, you acknowledge that:

- You have read this Disclaimer.
- You understand this Disclaimer.
- You accept this Disclaimer.
- You agree to use independent judgment.
- You understand that AI systems can make mistakes.
- You understand that VA provides educational coaching only.

=================================================================
16. CONTACT INFORMATION
=================================================================

For questions regarding this Disclaimer, contact:

VA (Vocal + Acuity)

Email: legal@yourdomain.com

Website: https://yourdomain.com

=================================================================
END OF PLATFORM DISCLAIMER
=================================================================
`;

export default function Page() {
  return <LegalDocument title="Platform Disclaimer" content={CONTENT} />;
}
